### ISSUE TITLE
Proposal for Improvement: Enclosing Header Text within Anchor Links

### ISSUE THREAD

**Issue by drumsta** [abhinav/goldmark-anchor#82]
I would like to propose an improvement for your extension: the ability to configure it to enclose the header text within the anchoring link itself.

Using the current solution, I haven't found a graceful way to hide the anchor symbol by default and only show it when needed. While I can hide and show the anchor symbol using CSS in two ways, both methods present issues:

1. Hiding the anchor symbol using `opacity: 0`: Setting opacity to 0 and back to 1 on hover works visually. However, accessibility checkers flag all anchor links for a poor contrast ratio (1:1) due to the opacity setting.

2. Hiding the anchor symbol using `visibility: hidden`: Setting visibility to `hidden` and back to `visible` on hover doesn't trigger accessibility issues regarding contrast. However, it causes problems with keyboard navigation; the headers are not selectable because the anchor links are not visible and therefore not focusable via keyboard. The same issue exists using the `display: none` approach.

The solution I am proposing is based on an approach I observed on the MDN Web Docs website. You can see this implemented on any page with headings, for example: https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/a. The headings are structured like this:

```html
<h2 id="try_it">
  <a href="#try_it">Try it</a>
</h2>
```

With this structure, the anchor symbol's hiding and showing, along with the actual anchor symbol character, can be managed purely through CSS, as demonstrated by the relevant code from the MDN CSS file:

```css
.anchor {
  &::before {
    color: var(--text-inactive);
    content: "#";
    display: inline-block;
    font-size: 0.7em;
    line-height: 1;
    margin-left: -0.8em;
    text-decoration: none;
    visibility: hidden;
    width: 0.8em;
  }

  &:hover {
    &::before {
      visibility: visible;
    }
  }
}
```

Note: This CSS uses SCSS-like nesting, but it is just for the illustrative purpose.

To implement this functionality in your extension, two changes would be necessary:

1. An option to instruct the extension to wrap the header text within the anchor link (`<a>` tag).
2. The ability to define an empty or null anchor character, as no additional character needs to be emitted by the extension; the symbol would be generated via CSS `::before` pseudo-element.

I believe this change would improve both the visual user experience and the accessibility of the generated anchor links.

Thank you for considering this proposal.
